# Generated by Django 5.2 on 2025-07-30 11:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerceapp', '0004_status'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Status',
        ),
    ]
